version: "3.8"

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: always
    environment:
      - TRAEFIK_DOMAIN=example.com
      - TRAEFIK_EMAIL=testn8n@gmail.com
      - TRAEFIK_DASHBOARD=true
      - TRAEFIK_DOCKER=true
      - TRAEFIK_FILE_DIRECTORY=/etc/traefik/dynamic
      - TRAEFIK_FILE_WATCH=true
      - TRAEFIK_WEB_ADDRESS=:80
      - TRAEFIK_WEBSECURE_ADDRESS=:443
      - TRAEFIK_ACME_TLSCHALLENGE=true
      - TRAEFIK_ACME_STORAGE=/letsencrypt/acme.json
    command:
      - "--api.dashboard=${TRAEFIK_DASHBOARD}"
      - "--providers.docker=${TRAEFIK_DOCKER}"
      - "--providers.file.directory=${TRAEFIK_FILE_DIRECTORY}"
      - "--providers.file.watch=${TRAEFIK_FILE_WATCH}"
      - "--entrypoints.web.address=${TRAEFIK_WEB_ADDRESS}"
      - "--entrypoints.websecure.address=${TRAEFIK_WEBSECURE_ADDRESS}"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=${TRAEFIK_ACME_TLSCHALLENGE}"
      - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=${TRAEFIK_ACME_STORAGE}"
    networks:
      - traefik_network
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./auth:/auth"
      - "./dynamic:/etc/traefik/dynamic"
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/auth/.htpasswd"

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/log:/var/log:ro
      - ./fail2ban:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=UTC
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=30d
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge
