version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: "n8n"
    restart: always
    env_file:
      - ./n8n.env
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge 