version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: "n8n-postgres"
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge 